services:
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8070:8080
    networks:
      - listmonk-dev
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    networks:
      - listmonk-dev

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - listmonk-dev
    environment:
      - POSTGRES_PASSWORD=listmonk-dev
      - POSTGRES_USER=listmonk-dev
      - POSTGRES_DB=listmonk-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk-dev -d listmonk-dev"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - type: volume
        source: listmonk-dev-db
        target: /var/lib/postgresql/data

  backend:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-backend-docker"]
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../:/app
      - go-mod-cache:/go/pkg/mod/cache
    networks:
      - listmonk-dev
    restart: unless-stopped

  front:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["/app/dev/start-frontend.sh"]
    ports:
      - "8080:8080"
    environment:
      - LISTMONK_API_URL=http://backend:9000
    depends_on:
      - backend
    volumes:
      - ../:/app
      - frontend-node-modules:/app/frontend/node_modules
      - email-builder-node-modules:/app/frontend/email-builder/node_modules
    networks:
      - listmonk-dev
    restart: unless-stopped

volumes:
  listmonk-dev-db:
  frontend-node-modules:
  email-builder-node-modules:
  go-mod-cache:

networks:
  listmonk-dev:
